DROP TABLE IF EXISTS persistent_logins;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id       bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email    text    NOT NULL UNIQUE,
    password text    NOT NULL,
    verified boolean NOT NULL DEFAULT FALSE,
    role     text
);

CREATE TABLE IF NOT EXISTS items
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint REFERENCES users (id) ON DELETE CASCADE,
    returned    boolean NOT NULL DEFAULT FALSE,
    type        text    NOT NULL,
    category    text    NOT NULL,
    title       text    NOT NULL,
    whom        text    NOT NULL,
    date        date    NOT NULL,
    due_date    date,
    description text
);

CREATE TABLE IF NOT EXISTS settings
(
    user_id            bigint PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    language_code      text,
    homepage_item_type text,
    items_per_page     text,
    sort_by            text,
    sort_direction     text
);

CREATE TABLE IF NOT EXISTS persistent_logins
(
    username  text      NOT NULL,
    series    text primary key,
    token     text      NOT NULL,
    last_used timestamp NOT NULL
);